package com.wjx.ehr.attendance.entity;

public class Attendance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.rule_date
     *
     * @mbggenerated
     */
    private Float ruleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.real_date
     *
     * @mbggenerated
     */
    private Float realDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.sick_leave
     *
     * @mbggenerated
     */
    private Float sickLeave;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.casual_leave
     *
     * @mbggenerated
     */
    private Float casualLeave;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.annual_leave
     *
     * @mbggenerated
     */
    private Float annualLeave;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.rest
     *
     * @mbggenerated
     */
    private Float rest;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.id
     *
     * @return the value of attendance.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.id
     *
     * @param id the value for attendance.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.code
     *
     * @return the value of attendance.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.code
     *
     * @param code the value for attendance.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.name
     *
     * @return the value of attendance.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.name
     *
     * @param name the value for attendance.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.rule_date
     *
     * @return the value of attendance.rule_date
     *
     * @mbggenerated
     */
    public Float getRuleDate() {
        return ruleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.rule_date
     *
     * @param ruleDate the value for attendance.rule_date
     *
     * @mbggenerated
     */
    public void setRuleDate(Float ruleDate) {
        this.ruleDate = ruleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.real_date
     *
     * @return the value of attendance.real_date
     *
     * @mbggenerated
     */
    public Float getRealDate() {
        return realDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.real_date
     *
     * @param realDate the value for attendance.real_date
     *
     * @mbggenerated
     */
    public void setRealDate(Float realDate) {
        this.realDate = realDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.sick_leave
     *
     * @return the value of attendance.sick_leave
     *
     * @mbggenerated
     */
    public Float getSickLeave() {
        return sickLeave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.sick_leave
     *
     * @param sickLeave the value for attendance.sick_leave
     *
     * @mbggenerated
     */
    public void setSickLeave(Float sickLeave) {
        this.sickLeave = sickLeave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.casual_leave
     *
     * @return the value of attendance.casual_leave
     *
     * @mbggenerated
     */
    public Float getCasualLeave() {
        return casualLeave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.casual_leave
     *
     * @param casualLeave the value for attendance.casual_leave
     *
     * @mbggenerated
     */
    public void setCasualLeave(Float casualLeave) {
        this.casualLeave = casualLeave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.annual_leave
     *
     * @return the value of attendance.annual_leave
     *
     * @mbggenerated
     */
    public Float getAnnualLeave() {
        return annualLeave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.annual_leave
     *
     * @param annualLeave the value for attendance.annual_leave
     *
     * @mbggenerated
     */
    public void setAnnualLeave(Float annualLeave) {
        this.annualLeave = annualLeave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.rest
     *
     * @return the value of attendance.rest
     *
     * @mbggenerated
     */
    public Float getRest() {
        return rest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.rest
     *
     * @param rest the value for attendance.rest
     *
     * @mbggenerated
     */
    public void setRest(Float rest) {
        this.rest = rest;
    }
}