package com.wjx.ehr.system.entity;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.hire_date
     *
     * @mbggenerated
     */
    private Date hireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.dept
     *
     * @mbggenerated
     */
    private String dept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id_number
     *
     * @mbggenerated
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.account_properties
     *
     * @mbggenerated
     */
    private String accountProperties;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.first_dept
     *
     * @mbggenerated
     */
    private String firstDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.birth_date
     *
     * @mbggenerated
     */
    private Date birthDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.education
     *
     * @mbggenerated
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.school
     *
     * @mbggenerated
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.left_date
     *
     * @mbggenerated
     */
    private Date leftDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.bank_number
     *
     * @mbggenerated
     */
    private String bankNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.cost_incidence
     *
     * @mbggenerated
     */
    private String costIncidence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.post
     *
     * @mbggenerated
     */
    private String post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.rank
     *
     * @mbggenerated
     */
    private String rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.positive_time
     *
     * @mbggenerated
     */
    private Date positiveTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.name
     *
     * @return the value of user_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.name
     *
     * @param name the value for user_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.code
     *
     * @return the value of user_info.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.code
     *
     * @param code the value for user_info.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.hire_date
     *
     * @return the value of user_info.hire_date
     *
     * @mbggenerated
     */
    public Date getHireDate() {
        return hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.hire_date
     *
     * @param hireDate the value for user_info.hire_date
     *
     * @mbggenerated
     */
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.dept
     *
     * @return the value of user_info.dept
     *
     * @mbggenerated
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.dept
     *
     * @param dept the value for user_info.dept
     *
     * @mbggenerated
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id_number
     *
     * @return the value of user_info.id_number
     *
     * @mbggenerated
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id_number
     *
     * @param idNumber the value for user_info.id_number
     *
     * @mbggenerated
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.city
     *
     * @return the value of user_info.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.city
     *
     * @param city the value for user_info.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.account_properties
     *
     * @return the value of user_info.account_properties
     *
     * @mbggenerated
     */
    public String getAccountProperties() {
        return accountProperties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.account_properties
     *
     * @param accountProperties the value for user_info.account_properties
     *
     * @mbggenerated
     */
    public void setAccountProperties(String accountProperties) {
        this.accountProperties = accountProperties == null ? null : accountProperties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.status
     *
     * @return the value of user_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.status
     *
     * @param status the value for user_info.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.first_dept
     *
     * @return the value of user_info.first_dept
     *
     * @mbggenerated
     */
    public String getFirstDept() {
        return firstDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.first_dept
     *
     * @param firstDept the value for user_info.first_dept
     *
     * @mbggenerated
     */
    public void setFirstDept(String firstDept) {
        this.firstDept = firstDept == null ? null : firstDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gender
     *
     * @return the value of user_info.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gender
     *
     * @param gender the value for user_info.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.birth_date
     *
     * @return the value of user_info.birth_date
     *
     * @mbggenerated
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.birth_date
     *
     * @param birthDate the value for user_info.birth_date
     *
     * @mbggenerated
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.education
     *
     * @return the value of user_info.education
     *
     * @mbggenerated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.education
     *
     * @param education the value for user_info.education
     *
     * @mbggenerated
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.school
     *
     * @return the value of user_info.school
     *
     * @mbggenerated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.school
     *
     * @param school the value for user_info.school
     *
     * @mbggenerated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.left_date
     *
     * @return the value of user_info.left_date
     *
     * @mbggenerated
     */
    public Date getLeftDate() {
        return leftDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.left_date
     *
     * @param leftDate the value for user_info.left_date
     *
     * @mbggenerated
     */
    public void setLeftDate(Date leftDate) {
        this.leftDate = leftDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.bank_number
     *
     * @return the value of user_info.bank_number
     *
     * @mbggenerated
     */
    public String getBankNumber() {
        return bankNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.bank_number
     *
     * @param bankNumber the value for user_info.bank_number
     *
     * @mbggenerated
     */
    public void setBankNumber(String bankNumber) {
        this.bankNumber = bankNumber == null ? null : bankNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.cost_incidence
     *
     * @return the value of user_info.cost_incidence
     *
     * @mbggenerated
     */
    public String getCostIncidence() {
        return costIncidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.cost_incidence
     *
     * @param costIncidence the value for user_info.cost_incidence
     *
     * @mbggenerated
     */
    public void setCostIncidence(String costIncidence) {
        this.costIncidence = costIncidence == null ? null : costIncidence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.post
     *
     * @return the value of user_info.post
     *
     * @mbggenerated
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.post
     *
     * @param post the value for user_info.post
     *
     * @mbggenerated
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.rank
     *
     * @return the value of user_info.rank
     *
     * @mbggenerated
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.rank
     *
     * @param rank the value for user_info.rank
     *
     * @mbggenerated
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.positive_time
     *
     * @return the value of user_info.positive_time
     *
     * @mbggenerated
     */
    public Date getPositiveTime() {
        return positiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.positive_time
     *
     * @param positiveTime the value for user_info.positive_time
     *
     * @mbggenerated
     */
    public void setPositiveTime(Date positiveTime) {
        this.positiveTime = positiveTime;
    }
}