package com.wjx.ehr.salary.dao;

import java.util.List;
import java.util.Map;

import com.wjx.ehr.salary.entity.SocialSecurityStandard;

public interface SocialSecurityStandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_security_standard
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_security_standard
     *
     * @mbggenerated
     */
    int insert(SocialSecurityStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_security_standard
     *
     * @mbggenerated
     */
    int insertSelective(SocialSecurityStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_security_standard
     *
     * @mbggenerated
     */
    SocialSecurityStandard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_security_standard
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SocialSecurityStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_security_standard
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SocialSecurityStandard record);
    
    List<SocialSecurityStandard> selectByMap(Map<Object, Object> map);
}