package com.wjx.ehr.salary.entity;

import java.util.Date;

public class Salary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.id_number
     *
     * @mbggenerated
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.cost_incidence
     *
     * @mbggenerated
     */
    private String costIncidence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.dept
     *
     * @mbggenerated
     */
    private String dept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.first_dept
     *
     * @mbggenerated
     */
    private String firstDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.post
     *
     * @mbggenerated
     */
    private String post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.rank
     *
     * @mbggenerated
     */
    private String rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.hire_date
     *
     * @mbggenerated
     */
    private Date hireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.positive_time
     *
     * @mbggenerated
     */
    private Date positiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.left_date
     *
     * @mbggenerated
     */
    private Date leftDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.positive_salary
     *
     * @mbggenerated
     */
    private Double positiveSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.try_salary
     *
     * @mbggenerated
     */
    private Double trySalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.day_salary
     *
     * @mbggenerated
     */
    private Double daySalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.real_day
     *
     * @mbggenerated
     */
    private Double realDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.shuld_totle
     *
     * @mbggenerated
     */
    private Double shuldTotle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.person_pension
     *
     * @mbggenerated
     */
    private Double personPension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.person_bear
     *
     * @mbggenerated
     */
    private Double personBear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.person_medical
     *
     * @mbggenerated
     */
    private Double personMedical;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.person_unemployment
     *
     * @mbggenerated
     */
    private Double personUnemployment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.person_injury
     *
     * @mbggenerated
     */
    private Double personInjury;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.person_reserved_funds
     *
     * @mbggenerated
     */
    private Double personReservedFunds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.company_pension
     *
     * @mbggenerated
     */
    private Double companyPension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.company_bear
     *
     * @mbggenerated
     */
    private Double companyBear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.company_medical
     *
     * @mbggenerated
     */
    private Double companyMedical;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.company_unemployment
     *
     * @mbggenerated
     */
    private Double companyUnemployment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.company_injury
     *
     * @mbggenerated
     */
    private Double companyInjury;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.company_reserved_funds
     *
     * @mbggenerated
     */
    private Double companyReservedFunds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.individual_income_tax
     *
     * @mbggenerated
     */
    private Double individualIncomeTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.tax_salary
     *
     * @mbggenerated
     */
    private Double taxSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.real_salary
     *
     * @mbggenerated
     */
    private Double realSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.before_tax
     *
     * @mbggenerated
     */
    private Double beforeTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.salary_date
     *
     * @mbggenerated
     */
    private Date salaryDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.id
     *
     * @return the value of salary.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.id
     *
     * @param id the value for salary.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.code
     *
     * @return the value of salary.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.code
     *
     * @param code the value for salary.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.name
     *
     * @return the value of salary.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.name
     *
     * @param name the value for salary.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.id_number
     *
     * @return the value of salary.id_number
     *
     * @mbggenerated
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.id_number
     *
     * @param idNumber the value for salary.id_number
     *
     * @mbggenerated
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.city
     *
     * @return the value of salary.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.city
     *
     * @param city the value for salary.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.cost_incidence
     *
     * @return the value of salary.cost_incidence
     *
     * @mbggenerated
     */
    public String getCostIncidence() {
        return costIncidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.cost_incidence
     *
     * @param costIncidence the value for salary.cost_incidence
     *
     * @mbggenerated
     */
    public void setCostIncidence(String costIncidence) {
        this.costIncidence = costIncidence == null ? null : costIncidence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.dept
     *
     * @return the value of salary.dept
     *
     * @mbggenerated
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.dept
     *
     * @param dept the value for salary.dept
     *
     * @mbggenerated
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.first_dept
     *
     * @return the value of salary.first_dept
     *
     * @mbggenerated
     */
    public String getFirstDept() {
        return firstDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.first_dept
     *
     * @param firstDept the value for salary.first_dept
     *
     * @mbggenerated
     */
    public void setFirstDept(String firstDept) {
        this.firstDept = firstDept == null ? null : firstDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.post
     *
     * @return the value of salary.post
     *
     * @mbggenerated
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.post
     *
     * @param post the value for salary.post
     *
     * @mbggenerated
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.rank
     *
     * @return the value of salary.rank
     *
     * @mbggenerated
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.rank
     *
     * @param rank the value for salary.rank
     *
     * @mbggenerated
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.hire_date
     *
     * @return the value of salary.hire_date
     *
     * @mbggenerated
     */
    public Date getHireDate() {
        return hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.hire_date
     *
     * @param hireDate the value for salary.hire_date
     *
     * @mbggenerated
     */
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.positive_time
     *
     * @return the value of salary.positive_time
     *
     * @mbggenerated
     */
    public Date getPositiveTime() {
        return positiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.positive_time
     *
     * @param positiveTime the value for salary.positive_time
     *
     * @mbggenerated
     */
    public void setPositiveTime(Date positiveTime) {
        this.positiveTime = positiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.left_date
     *
     * @return the value of salary.left_date
     *
     * @mbggenerated
     */
    public Date getLeftDate() {
        return leftDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.left_date
     *
     * @param leftDate the value for salary.left_date
     *
     * @mbggenerated
     */
    public void setLeftDate(Date leftDate) {
        this.leftDate = leftDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.type
     *
     * @return the value of salary.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.type
     *
     * @param type the value for salary.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.positive_salary
     *
     * @return the value of salary.positive_salary
     *
     * @mbggenerated
     */
    public Double getPositiveSalary() {
        return positiveSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.positive_salary
     *
     * @param positiveSalary the value for salary.positive_salary
     *
     * @mbggenerated
     */
    public void setPositiveSalary(Double positiveSalary) {
        this.positiveSalary = positiveSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.try_salary
     *
     * @return the value of salary.try_salary
     *
     * @mbggenerated
     */
    public Double getTrySalary() {
        return trySalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.try_salary
     *
     * @param trySalary the value for salary.try_salary
     *
     * @mbggenerated
     */
    public void setTrySalary(Double trySalary) {
        this.trySalary = trySalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.day_salary
     *
     * @return the value of salary.day_salary
     *
     * @mbggenerated
     */
    public Double getDaySalary() {
        return daySalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.day_salary
     *
     * @param daySalary the value for salary.day_salary
     *
     * @mbggenerated
     */
    public void setDaySalary(Double daySalary) {
        this.daySalary = daySalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.real_day
     *
     * @return the value of salary.real_day
     *
     * @mbggenerated
     */
    public Double getRealDay() {
        return realDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.real_day
     *
     * @param realDay the value for salary.real_day
     *
     * @mbggenerated
     */
    public void setRealDay(Double realDay) {
        this.realDay = realDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.shuld_totle
     *
     * @return the value of salary.shuld_totle
     *
     * @mbggenerated
     */
    public Double getShuldTotle() {
        return shuldTotle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.shuld_totle
     *
     * @param shuldTotle the value for salary.shuld_totle
     *
     * @mbggenerated
     */
    public void setShuldTotle(Double shuldTotle) {
        this.shuldTotle = shuldTotle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.person_pension
     *
     * @return the value of salary.person_pension
     *
     * @mbggenerated
     */
    public Double getPersonPension() {
        return personPension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.person_pension
     *
     * @param personPension the value for salary.person_pension
     *
     * @mbggenerated
     */
    public void setPersonPension(Double personPension) {
        this.personPension = personPension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.person_bear
     *
     * @return the value of salary.person_bear
     *
     * @mbggenerated
     */
    public Double getPersonBear() {
        return personBear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.person_bear
     *
     * @param personBear the value for salary.person_bear
     *
     * @mbggenerated
     */
    public void setPersonBear(Double personBear) {
        this.personBear = personBear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.person_medical
     *
     * @return the value of salary.person_medical
     *
     * @mbggenerated
     */
    public Double getPersonMedical() {
        return personMedical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.person_medical
     *
     * @param personMedical the value for salary.person_medical
     *
     * @mbggenerated
     */
    public void setPersonMedical(Double personMedical) {
        this.personMedical = personMedical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.person_unemployment
     *
     * @return the value of salary.person_unemployment
     *
     * @mbggenerated
     */
    public Double getPersonUnemployment() {
        return personUnemployment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.person_unemployment
     *
     * @param personUnemployment the value for salary.person_unemployment
     *
     * @mbggenerated
     */
    public void setPersonUnemployment(Double personUnemployment) {
        this.personUnemployment = personUnemployment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.person_injury
     *
     * @return the value of salary.person_injury
     *
     * @mbggenerated
     */
    public Double getPersonInjury() {
        return personInjury;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.person_injury
     *
     * @param personInjury the value for salary.person_injury
     *
     * @mbggenerated
     */
    public void setPersonInjury(Double personInjury) {
        this.personInjury = personInjury;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.person_reserved_funds
     *
     * @return the value of salary.person_reserved_funds
     *
     * @mbggenerated
     */
    public Double getPersonReservedFunds() {
        return personReservedFunds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.person_reserved_funds
     *
     * @param personReservedFunds the value for salary.person_reserved_funds
     *
     * @mbggenerated
     */
    public void setPersonReservedFunds(Double personReservedFunds) {
        this.personReservedFunds = personReservedFunds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.company_pension
     *
     * @return the value of salary.company_pension
     *
     * @mbggenerated
     */
    public Double getCompanyPension() {
        return companyPension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.company_pension
     *
     * @param companyPension the value for salary.company_pension
     *
     * @mbggenerated
     */
    public void setCompanyPension(Double companyPension) {
        this.companyPension = companyPension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.company_bear
     *
     * @return the value of salary.company_bear
     *
     * @mbggenerated
     */
    public Double getCompanyBear() {
        return companyBear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.company_bear
     *
     * @param companyBear the value for salary.company_bear
     *
     * @mbggenerated
     */
    public void setCompanyBear(Double companyBear) {
        this.companyBear = companyBear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.company_medical
     *
     * @return the value of salary.company_medical
     *
     * @mbggenerated
     */
    public Double getCompanyMedical() {
        return companyMedical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.company_medical
     *
     * @param companyMedical the value for salary.company_medical
     *
     * @mbggenerated
     */
    public void setCompanyMedical(Double companyMedical) {
        this.companyMedical = companyMedical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.company_unemployment
     *
     * @return the value of salary.company_unemployment
     *
     * @mbggenerated
     */
    public Double getCompanyUnemployment() {
        return companyUnemployment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.company_unemployment
     *
     * @param companyUnemployment the value for salary.company_unemployment
     *
     * @mbggenerated
     */
    public void setCompanyUnemployment(Double companyUnemployment) {
        this.companyUnemployment = companyUnemployment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.company_injury
     *
     * @return the value of salary.company_injury
     *
     * @mbggenerated
     */
    public Double getCompanyInjury() {
        return companyInjury;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.company_injury
     *
     * @param companyInjury the value for salary.company_injury
     *
     * @mbggenerated
     */
    public void setCompanyInjury(Double companyInjury) {
        this.companyInjury = companyInjury;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.company_reserved_funds
     *
     * @return the value of salary.company_reserved_funds
     *
     * @mbggenerated
     */
    public Double getCompanyReservedFunds() {
        return companyReservedFunds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.company_reserved_funds
     *
     * @param companyReservedFunds the value for salary.company_reserved_funds
     *
     * @mbggenerated
     */
    public void setCompanyReservedFunds(Double companyReservedFunds) {
        this.companyReservedFunds = companyReservedFunds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.individual_income_tax
     *
     * @return the value of salary.individual_income_tax
     *
     * @mbggenerated
     */
    public Double getIndividualIncomeTax() {
        return individualIncomeTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.individual_income_tax
     *
     * @param individualIncomeTax the value for salary.individual_income_tax
     *
     * @mbggenerated
     */
    public void setIndividualIncomeTax(Double individualIncomeTax) {
        this.individualIncomeTax = individualIncomeTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.tax_salary
     *
     * @return the value of salary.tax_salary
     *
     * @mbggenerated
     */
    public Double getTaxSalary() {
        return taxSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.tax_salary
     *
     * @param taxSalary the value for salary.tax_salary
     *
     * @mbggenerated
     */
    public void setTaxSalary(Double taxSalary) {
        this.taxSalary = taxSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.real_salary
     *
     * @return the value of salary.real_salary
     *
     * @mbggenerated
     */
    public Double getRealSalary() {
        return realSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.real_salary
     *
     * @param realSalary the value for salary.real_salary
     *
     * @mbggenerated
     */
    public void setRealSalary(Double realSalary) {
        this.realSalary = realSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.before_tax
     *
     * @return the value of salary.before_tax
     *
     * @mbggenerated
     */
    public Double getBeforeTax() {
        return beforeTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.before_tax
     *
     * @param beforeTax the value for salary.before_tax
     *
     * @mbggenerated
     */
    public void setBeforeTax(Double beforeTax) {
        this.beforeTax = beforeTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.salary_date
     *
     * @return the value of salary.salary_date
     *
     * @mbggenerated
     */
    public Date getSalaryDate() {
        return salaryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.salary_date
     *
     * @param salaryDate the value for salary.salary_date
     *
     * @mbggenerated
     */
    public void setSalaryDate(Date salaryDate) {
        this.salaryDate = salaryDate;
    }
}