package com.wjx.ehr.salary.entity;

public class SocialSecurityStandard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security_standard.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security_standard.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security_standard.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security_standard.pension
     *
     * @mbggenerated
     */
    private Double pension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security_standard.bear
     *
     * @mbggenerated
     */
    private Double bear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security_standard.medical
     *
     * @mbggenerated
     */
    private Double medical;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security_standard.unemployment
     *
     * @mbggenerated
     */
    private Double unemployment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security_standard.injury
     *
     * @mbggenerated
     */
    private Double injury;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security_standard.reserved_funds
     *
     * @mbggenerated
     */
    private Double reservedFunds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column social_security_standard.com
     *
     * @mbggenerated
     */
    private String com;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security_standard.id
     *
     * @return the value of social_security_standard.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security_standard.id
     *
     * @param id the value for social_security_standard.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security_standard.city
     *
     * @return the value of social_security_standard.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security_standard.city
     *
     * @param city the value for social_security_standard.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security_standard.type
     *
     * @return the value of social_security_standard.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security_standard.type
     *
     * @param type the value for social_security_standard.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security_standard.pension
     *
     * @return the value of social_security_standard.pension
     *
     * @mbggenerated
     */
    public Double getPension() {
        return pension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security_standard.pension
     *
     * @param pension the value for social_security_standard.pension
     *
     * @mbggenerated
     */
    public void setPension(Double pension) {
        this.pension = pension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security_standard.bear
     *
     * @return the value of social_security_standard.bear
     *
     * @mbggenerated
     */
    public Double getBear() {
        return bear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security_standard.bear
     *
     * @param bear the value for social_security_standard.bear
     *
     * @mbggenerated
     */
    public void setBear(Double bear) {
        this.bear = bear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security_standard.medical
     *
     * @return the value of social_security_standard.medical
     *
     * @mbggenerated
     */
    public Double getMedical() {
        return medical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security_standard.medical
     *
     * @param medical the value for social_security_standard.medical
     *
     * @mbggenerated
     */
    public void setMedical(Double medical) {
        this.medical = medical;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security_standard.unemployment
     *
     * @return the value of social_security_standard.unemployment
     *
     * @mbggenerated
     */
    public Double getUnemployment() {
        return unemployment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security_standard.unemployment
     *
     * @param unemployment the value for social_security_standard.unemployment
     *
     * @mbggenerated
     */
    public void setUnemployment(Double unemployment) {
        this.unemployment = unemployment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security_standard.injury
     *
     * @return the value of social_security_standard.injury
     *
     * @mbggenerated
     */
    public Double getInjury() {
        return injury;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security_standard.injury
     *
     * @param injury the value for social_security_standard.injury
     *
     * @mbggenerated
     */
    public void setInjury(Double injury) {
        this.injury = injury;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security_standard.reserved_funds
     *
     * @return the value of social_security_standard.reserved_funds
     *
     * @mbggenerated
     */
    public Double getReservedFunds() {
        return reservedFunds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security_standard.reserved_funds
     *
     * @param reservedFunds the value for social_security_standard.reserved_funds
     *
     * @mbggenerated
     */
    public void setReservedFunds(Double reservedFunds) {
        this.reservedFunds = reservedFunds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column social_security_standard.com
     *
     * @return the value of social_security_standard.com
     *
     * @mbggenerated
     */
    public String getCom() {
        return com;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column social_security_standard.com
     *
     * @param com the value for social_security_standard.com
     *
     * @mbggenerated
     */
    public void setCom(String com) {
        this.com = com == null ? null : com.trim();
    }
}